apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    name: mysqldb-service
    app: login-application
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysqldb-pod
    app: login-application
